### ISSUE TITLE
Crash on invalid license (mpl 2.0)

### ISSUE THREAD

**Issue by DaniD3v** [projg2/pycargoebuild#24]
This is the traceback I got for https://github.com/done-devs/done

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/pycargoebuild", line 8, in <module>
    sys.exit(entry_point())
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/__main__.py", line 384, in entry_point
    sys.exit(main(*sys.argv))
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/__main__.py", line 331, in main
    ebuild = get_ebuild(
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/ebuild.py", line 218, in get_ebuild
    pkg_license=get_package_LICENSE(pkg_meta.license),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/ebuild.py", line 103, in get_package_LICENSE
    return format_license_var(spdx_to_ebuild(parsed_pkg_license),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/license.py", line 102, in spdx_to_ebuild
    return " ".join(sub(spdx, in_or=False))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/license.py", line 84, in sub
    mapped = symbol_to_ebuild(x).split()
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/license.py", line 36, in symbol_to_ebuild
    return MAPPING[full_key]
           ~~~~~~~^^^^^^^^^^
KeyError: 'mpl 2.0'

**Comment by mgorny** [comment]
I suppose you're asking for user-friendly error messages?

**Comment by DaniD3v** [comment]
well yeah I don't really know what I'm supposed to do here.
Manually translate the license? Add the license to your /var/db/repos/<repo>/licenses?

I can also PR a better error message myself if you tell me what I'm supposed to do here.
