### ISSUE TITLE
KeyError: 'checksum' on rustworkx-0.12.1

### ISSUE THREAD

**Issue by mgorny** [projg2/pycargoebuild#4]
Need to investigate:

```pytb
$ pycargoebuild /tmp/mgorny-dev-scripts/portage/dev-python/rustworkx-0.12.1/work/rustworkx-0.12.1
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/pycargoebuild", line 8, in <module>
    sys.exit(entry_point())
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/__main__.py", line 176, in entry_point
    sys.exit(main(*sys.argv))
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pycargoebuild/__main__.py", line 79, in main
    crates.update(get_crates(f, exclude=[pkg_metas[-1].name]))
  File "/usr/lib/python3.11/site-packages/pycargoebuild/cargo.py", line 55, in <genexpr>
    return (Crate(name=p["name"], version=p["version"], checksum=p["checksum"])
                                                                 ~^^^^^^^^^^^^
KeyError: 'checksum'
```

**Comment by mgorny** [comment]
Ah, workspaces apparently!
